package Entity;

public class RideInformation {
    
    //will be auto generated by mysql database
    private Integer id;
    
    private Integer driverId;
    
    private Integer rideTakerId;
    
    private Double driverRating;
    
    private Double rideTakerRating;

    public RideInformation() {
    }

    public RideInformation(Integer id, Integer driverId, Integer rideTakerId, Double driverRating, Double rideTakerRating) {
        this.id = id;
        this.driverId = driverId;
        this.rideTakerId = rideTakerId;
        this.driverRating = driverRating;
        this.rideTakerRating = rideTakerRating;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getDriverId() {
        return driverId;
    }

    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    public Integer getRideTakerId() {
        return rideTakerId;
    }

    public void setRideTakerId(Integer rideTakerId) {
        this.rideTakerId = rideTakerId;
    }

    public Double getDriverRating() {
        return driverRating;
    }

    public void setDriverRating(Double driverRating) {
        this.driverRating = driverRating;
    }

    public Double getRideTakerRating() {
        return rideTakerRating;
    }

    public void setRideTakerRating(Double rideTakerRating) {
        this.rideTakerRating = rideTakerRating;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("RideInformation{");
        sb.append("id=").append(id);
        sb.append(", driverId=").append(driverId);
        sb.append(", rideTakerId=").append(rideTakerId);
        sb.append(", driverRating=").append(driverRating);
        sb.append(", rideTakerRating=").append(rideTakerRating);
        sb.append('}');
        return sb.toString();
    }
}
